name: 反馈问题
description: 反馈问题
title: "🐞 反馈问题：请填写标题"
labels: ["bug"]
assignees:
  -

body:
  - type: checkboxes
    id: checklist
    attributes:
      label: 请先确认以下事项：
      options:
        - label: 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
          required: true
        - label: 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
          required: true
        - label: Easydict 已升级到最新版本
          required: true

  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 请尽量清晰、详细地描述问题。如果涉及 UI，请提供截图，若问题比较复杂，最好能提供录屏，方便开发者排查。如果是应用崩溃问题，请提供崩溃日志，菜单图标 -> 帮助 -> 导出日志。
      placeholder: 问题描述
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 重现步骤
      description: 请描述如何重现该问题。如果该问题是偶发性的，或者需要特定的操作步骤才能重现，请尽量详细地描述。
      placeholder:
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期望结果
      description: 请描述您期望的结果。
      placeholder:
    validations:
      required: true

  - type: textarea
    id: resolution
    attributes:
      label: 解决方案（可选）
      description: 对于该问题，您有什么预想的解决方案，或者建议？
      placeholder:

  - type: input
    id: device
    attributes:
      label: 设备信息 && 操作系统版本
      description: 如果遇到比较奇怪的问题，请提供设备信息和操作系统版本，方便开发者排查
      placeholder: Apple M1 Pro, macOS 11.2.3

  - type: checkboxes
    id: PR
    attributes:
      label: 是否愿意提交 PR 解决该问题？
      description: 我们非常欢迎您提交 PR，当开发者人力不足时，提交 PR 是解决该问题最快的方式。如果对 Objective-C 语言不熟悉，可以尝试使用 ChatGPT，也许它能帮到你。
      options:
        - label: 我愿意提交 PR!
